import { onAuthStateChanged } from "firebase/auth";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { Header, Sidebar } from "../../components";
import { auth } from "../../firebase/config";

const SongDetails = () => {
  const router = useRouter();
  const [loading, setLoading] = useState(true);
  const [user, setUser] = useState(null);
  const { id } = router.query;

  // check user auth state
  useEffect(() => {
    onAuthStateChanged(auth, (user) => {
      if (user) {
        // User is signed in, see docs for a list of available properties
        setUser(user);
      } else {
        router.push("/auth/login");
      }
      setLoading(false);
    });
  }, []);

  if (loading || !user) return;
  return (
    <>
      <Head>
        <title>Details - Spotify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* Sidebar */}
        <Sidebar user={user} details={true} />

        {/* Header */}
        <Header user={user} details={true} />
      </main>
    </>
  );
};

export default SongDetails;
