import { onAuthStateChanged } from "firebase/auth";
import Head from "next/head";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { Header, Sidebar, Details } from "../../components";
import { auth } from "../../firebase/config";
import { options } from "../../utils/urlOptions";

const SongDetails = () => {
  const router = useRouter();
  const [songDetails, setSongDetails] = useState(null);
  const [loading, setLoading] = useState(true);
  const [user, setUser] = useState(null);
  const { id } = router.query;

  // check user auth state
  useEffect(() => {
    onAuthStateChanged(auth, (user) => {
      if (user) {
        // User is signed in, see docs for a list of available properties
        setUser(user);
      } else {
        router.push("/auth/login");
      }
      setLoading(false);
    });
  }, []);

  // fetch details of the song
  useEffect(() => {
    const fetchSongDetails = async () => {
      const fetchDetails = await fetch(
        `https://shazam.p.rapidapi.com/songs/get-details?key=${id}&locale=en-US`,
        options
      );
      const detailsResponse = await fetchDetails.json();
      setSongDetails(detailsResponse);
    };
    fetchSongDetails();
  }, [id]);

  if (loading || !user) return;
  return (
    <>
      <Head>
        <title>Details - Spotify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* Sidebar */}
        <Sidebar user={user} details={true} />

        {/* Header */}
        <Header user={user} details={true} />

        {/* Details */}
        <Details songDetails={songDetails} />
      </main>
    </>
  );
};

export default SongDetails;
