import Head from "next/head";
import Image from "next/image";
import { BsFacebook } from "react-icons/bs";
import { FcGoogle } from "react-icons/fc";
import Link from "next/link";

const Auth = ({ head }) => {
  return (
    <div>
      <Head>
        <title>{head} - Spotify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="text-center flex flex-col items-center justify-center">
        <div className="flex items-center text-green-500 my-6">
          <Image
            src="/img/logo.png"
            alt="spotify-logo"
            height={40}
            width={40}
          />
          <p className="text-3xl md:text-4xl ml-2 font-bold">Spotify</p>
        </div>

        <h1 className="font-bold text-3xl md:text-5xl w-[300px] md:w-[400px] mb-8">
          {head === "Login"
            ? "To continue, log in to Spotify."
            : "Sign up for free to start listening."}
        </h1>

        <button className="authBtn bg-blue-600 text-white mb-4">
          <BsFacebook className="text-2xl" />{" "}
          <span>{head === "Login" ? "Continue" : "Sign up"} with Facebook</span>
        </button>

        <button className="authBtn border-2 text-gray-600">
          <FcGoogle className="text-2xl" />{" "}
          <span>{head === "Login" ? "Continue" : "Sign up"} with Google</span>
        </button>

        <div className="flex items-center gap-2 mt-5 justify-center">
          <div className="line" />
          <p className="text-xl">or</p>
          <div className="line" />
        </div>

        <h2 className="mt-2 font-bold text-lg whitespace-nowrap mb-3">
          {head === "Login" ? "Login" : "Sign up"} with your email address
        </h2>

        <form>
          <div className="formGroup">
            <label htmlFor="email">
              {head === "Login" ? "Email address" : "What's your email?"}
            </label>
            <input
              className="input"
              type="email"
              id="email"
              placeholder="Enter your email."
            />
          </div>
          {head === "Signup" && (
            <div className="formGroup">
              <label htmlFor="confirmEmail">Confirm your email</label>
              <input
                className="input"
                type="email"
                id="confirmEmail"
                placeholder="Enter your email again."
              />
            </div>
          )}
          <div className="formGroup">
            <label htmlFor="password">
              {head === "Login" ? "Password" : "Create a password"}
            </label>
            <input
              className="input"
              type="password"
              id="password"
              placeholder={
                head === "Login" ? "Password." : "Create a password."
              }
            />
          </div>
          {head === "Signup" && (
            <div className="formGroup">
              <label htmlFor="confirmPassword">Confirm your password</label>
              <input
                className="input"
                type="password"
                id="confirmPassword"
                placeholder="Enter your password again."
              />
            </div>
          )}
          <button
            className="bg-green-400 px-10 py-3 mb-2 rounded-[30px] text-lg  font-bold hover:scale-110"
            type="submit"
          >
            {head === "Login" ? "LOG IN" : "SIGN UP"}
          </button>
          {head === "Signup" && (
            <p className="mb-8 text-lg">
              Have an account?
              <Link
                href="/auth/login"
                className="underline text-green-800 hover:text-green-600"
              >
                Log in
              </Link>
            </p>
          )}

          {head === "Login" && (
            <div>
              <h2 className="font-bold text-lg">Don&#39;t have an account?</h2>
              <button
                className="mt-3 mb-8 authBtn border-2 text-gray-600"
                type="button"
              >
                <Link href="/auth/signup">SIGN UP FOR SPOTIFY</Link>
              </button>
            </div>
          )}
        </form>
      </main>
    </div>
  );
};

export default Auth;
