import Head from "next/head";
import { Feeds, Header, Sidebar, Loader } from "../components";
import { onAuthStateChanged } from "firebase/auth";
import { auth } from "../firebase/config";
import { useState, useEffect } from "react";

export default function Home() {
  const [loading, setLoading] = useState(true);
  const [user, setUser] = useState(null);

  // Check User State
  useEffect(() => {
    setLoading(true);
    onAuthStateChanged(auth, (user) => {
      if (user) {
        setUser(user);
      } else {
        setUser(null);
      }
    });
    setLoading(false);
  }, []);

  if (loading) return <Loader />;
  return (
    <>
      <Head>
        <title>Home - Spotify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* Sidebar */}
        <Sidebar />

        {/* Header */}
        <Header user={user} />

        {/***** Feeds *****/}
        <Feeds />
      </main>
    </>
  );
}
