import Head from "next/head";
import {
  Feeds,
  Header,
  Sidebar,
  SignupFooter,
  SignupModal,
  LoggedFeeds,
} from "../components";
import { selectShowModal } from "../redux/slice/authSlice";
import { useSelector } from "react-redux";
import { useSession } from "next-auth/react";
import SpotifyWebApi from "spotify-web-api-node";
import { useEffect, useState } from "react";
import { useDispatch } from "react-redux";
import { GET_PLAYLISTS } from "../redux/slice/songSlice";
import useSpotify from "../hooks/useSpotify";

export default function Home() {
  const dispatch = useDispatch();
  const showModal = useSelector(selectShowModal);
  const { data: session } = useSession();
  const spotifyApi = useSpotify();

  //fetch user playlists
  useEffect(() => {
    if (spotifyApi.getAccessToken()) {
      spotifyApi.getUserPlaylists().then((playlists) => {
        dispatch(GET_PLAYLISTS(playlists.body.items));
      });
    }
  }, [session?.accessToken]);

  return (
    <>
      <Head>
        <title>Home - Spotify</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* Sidebar */}
        <Sidebar />

        {/* Header */}
        <Header />

        {/***** User logged out Feeds *****/}
        {!session && <Feeds />}

        {session && <LoggedFeeds />}

        {/* Signup Footer Component */}
        {!session && <SignupFooter />}

        {/* Signup Modal */}
        {showModal && <SignupModal />}
      </main>
    </>
  );
}
